version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nm-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app

  app:
    build: .
    container_name: nm-app
    expose:
      - "8080"
      - "9000"
    environment:
      - ENV_MODE=DEV
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: nm-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sjdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nm-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: