// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: project_nm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeGrpcItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeGrpcItem) Reset() {
	*x = TradeGrpcItem{}
	mi := &file_project_nm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeGrpcItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeGrpcItem) ProtoMessage() {}

func (x *TradeGrpcItem) ProtoReflect() protoreflect.Message {
	mi := &file_project_nm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeGrpcItem.ProtoReflect.Descriptor instead.
func (*TradeGrpcItem) Descriptor() ([]byte, []int) {
	return file_project_nm_proto_rawDescGZIP(), []int{0}
}

func (x *TradeGrpcItem) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *TradeGrpcItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeGrpcItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type TradeGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrpcUserInfo  *GRPCUserInfo          `protobuf:"bytes,1,opt,name=grpc_user_info,json=grpcUserInfo,proto3" json:"grpc_user_info,omitempty"`
	Items         []*TradeGrpcItem       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeGrpcRequest) Reset() {
	*x = TradeGrpcRequest{}
	mi := &file_project_nm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeGrpcRequest) ProtoMessage() {}

func (x *TradeGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_nm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeGrpcRequest.ProtoReflect.Descriptor instead.
func (*TradeGrpcRequest) Descriptor() ([]byte, []int) {
	return file_project_nm_proto_rawDescGZIP(), []int{1}
}

func (x *TradeGrpcRequest) GetGrpcUserInfo() *GRPCUserInfo {
	if x != nil {
		return x.GrpcUserInfo
	}
	return nil
}

func (x *TradeGrpcRequest) GetItems() []*TradeGrpcItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TradeGrpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint32                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeGrpcResponse) Reset() {
	*x = TradeGrpcResponse{}
	mi := &file_project_nm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeGrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeGrpcResponse) ProtoMessage() {}

func (x *TradeGrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_nm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeGrpcResponse.ProtoReflect.Descriptor instead.
func (*TradeGrpcResponse) Descriptor() ([]byte, []int) {
	return file_project_nm_proto_rawDescGZIP(), []int{2}
}

func (x *TradeGrpcResponse) GetMemberId() uint32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *TradeGrpcResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GRPCUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Schema        string                 `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPCUserInfo) Reset() {
	*x = GRPCUserInfo{}
	mi := &file_project_nm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCUserInfo) ProtoMessage() {}

func (x *GRPCUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_project_nm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCUserInfo.ProtoReflect.Descriptor instead.
func (*GRPCUserInfo) Descriptor() ([]byte, []int) {
	return file_project_nm_proto_rawDescGZIP(), []int{3}
}

func (x *GRPCUserInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GRPCUserInfo) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GRPCUserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GRPCUserInfo) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

var File_project_nm_proto protoreflect.FileDescriptor

var file_project_nm_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x5e, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x64, 0x65, 0x47,
	0x72, 0x70, 0x63, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x73, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x64, 0x65, 0x47,
	0x72, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0e, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x27, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x47, 0x72, 0x70, 0x63,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x48, 0x0a, 0x11, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x47, 0x72, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x6f, 0x0a, 0x0c, 0x47, 0x52, 0x50, 0x43, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x32, 0x4a, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x47, 0x72, 0x70, 0x63, 0x12, 0x3b, 0x0a, 0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x47, 0x72, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x47, 0x72, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_project_nm_proto_rawDescOnce sync.Once
	file_project_nm_proto_rawDescData []byte
)

func file_project_nm_proto_rawDescGZIP() []byte {
	file_project_nm_proto_rawDescOnce.Do(func() {
		file_project_nm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_nm_proto_rawDesc), len(file_project_nm_proto_rawDesc)))
	})
	return file_project_nm_proto_rawDescData
}

var file_project_nm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_project_nm_proto_goTypes = []any{
	(*TradeGrpcItem)(nil),     // 0: pb.TradeGrpcItem
	(*TradeGrpcRequest)(nil),  // 1: pb.TradeGrpcRequest
	(*TradeGrpcResponse)(nil), // 2: pb.TradeGrpcResponse
	(*GRPCUserInfo)(nil),      // 3: pb.GRPCUserInfo
}
var file_project_nm_proto_depIdxs = []int32{
	3, // 0: pb.TradeGrpcRequest.grpc_user_info:type_name -> pb.GRPCUserInfo
	0, // 1: pb.TradeGrpcRequest.items:type_name -> pb.TradeGrpcItem
	1, // 2: pb.ProjectGrpc.ExecuteOrder:input_type -> pb.TradeGrpcRequest
	2, // 3: pb.ProjectGrpc.ExecuteOrder:output_type -> pb.TradeGrpcResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_project_nm_proto_init() }
func file_project_nm_proto_init() {
	if File_project_nm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_nm_proto_rawDesc), len(file_project_nm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_nm_proto_goTypes,
		DependencyIndexes: file_project_nm_proto_depIdxs,
		MessageInfos:      file_project_nm_proto_msgTypes,
	}.Build()
	File_project_nm_proto = out.File
	file_project_nm_proto_goTypes = nil
	file_project_nm_proto_depIdxs = nil
}
