// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: project_nm.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectGrpc_ExecuteOrder_FullMethodName = "/pb.ProjectGrpc/ExecuteOrder"
)

// ProjectGrpcClient is the client API for ProjectGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectGrpcClient interface {
	ExecuteOrder(ctx context.Context, in *TradeGrpcRequest, opts ...grpc.CallOption) (*TradeGrpcResponse, error)
}

type projectGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectGrpcClient(cc grpc.ClientConnInterface) ProjectGrpcClient {
	return &projectGrpcClient{cc}
}

func (c *projectGrpcClient) ExecuteOrder(ctx context.Context, in *TradeGrpcRequest, opts ...grpc.CallOption) (*TradeGrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeGrpcResponse)
	err := c.cc.Invoke(ctx, ProjectGrpc_ExecuteOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectGrpcServer is the server API for ProjectGrpc service.
// All implementations must embed UnimplementedProjectGrpcServer
// for forward compatibility.
type ProjectGrpcServer interface {
	ExecuteOrder(context.Context, *TradeGrpcRequest) (*TradeGrpcResponse, error)
	mustEmbedUnimplementedProjectGrpcServer()
}

// UnimplementedProjectGrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectGrpcServer struct{}

func (UnimplementedProjectGrpcServer) ExecuteOrder(context.Context, *TradeGrpcRequest) (*TradeGrpcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteOrder not implemented")
}
func (UnimplementedProjectGrpcServer) mustEmbedUnimplementedProjectGrpcServer() {}
func (UnimplementedProjectGrpcServer) testEmbeddedByValue()                     {}

// UnsafeProjectGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectGrpcServer will
// result in compilation errors.
type UnsafeProjectGrpcServer interface {
	mustEmbedUnimplementedProjectGrpcServer()
}

func RegisterProjectGrpcServer(s grpc.ServiceRegistrar, srv ProjectGrpcServer) {
	// If the following call pancis, it indicates UnimplementedProjectGrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectGrpc_ServiceDesc, srv)
}

func _ProjectGrpc_ExecuteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectGrpcServer).ExecuteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectGrpc_ExecuteOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectGrpcServer).ExecuteOrder(ctx, req.(*TradeGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectGrpc_ServiceDesc is the grpc.ServiceDesc for ProjectGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ProjectGrpc",
	HandlerType: (*ProjectGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteOrder",
			Handler:    _ProjectGrpc_ExecuteOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "project_nm.proto",
}
